# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: Test
      run: go test -v ./...

    - name: Build Static Binary
      run: |
        CGO_ENABLED=0 go build -v -ldflags '-extldflags "-static"' -o reverse-ssh-x86-linux ./cmd/reverse-ssh/...

    - name: Build Static Binary (arm)
      run: |
        CGO_ENABLED=0 GOARCH=arm64 go build -v -ldflags '-extldflags "-static"' -o reverse-ssh-arm-linux ./cmd/reverse-ssh/...

    - name: Build Static Binary (arm darwin)
      run: |
        CGO_ENABLED=0 GOARCH=arm64 GOOS=darwin go build -v -ldflags '-extldflags "-static"' -o reverse-ssh-arm-darwin ./cmd/reverse-ssh/...
      

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: reverse-ssh
        path: |
          reverse-ssh-x86-linux
          reverse-ssh-arm-linux
          reverse-ssh-arm-darwin
